### ISSUE TITLE
Add recommendation for using 'controller as' syntax

### ISSUE THREAD

**Issue by yanivefraim** [mgechev/angularjs-style-guide#101]
There are plenty of reasons why you should prefer the use of 'controller as' syntax over regular 'controller'. 
Two interesting posts about it are:
1. http://toddmotto.com/digging-into-angulars-controller-as-syntax/ 
2. http://teropa.info/blog/2014/10/24/how-ive-improved-my-angular-apps-by-banning-ng-controller.html

I will be more than glad to add a PR for a section like this!

**Comment by mgechev** [comment]
Yes, it makes sense.
PRs are welcome!

**Comment by yanivefraim** [comment]
Awesome, I'm on it

**Comment by yanivefraim** [comment]
PR merged
