### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by jonkri** [mgechev/angularjs-style-guide#125]
What are the license terms for this guide? Or are they just proprietary/default copyright?

It would be nice if the terms for the guide made it free and open source. AngularJS itself uses the MIT license, so this might be a good choice.

The license terms should probably go into a LICENSE(.md) file at the root of the repository. They could also be briefly mentioned in the README file.

**Comment by mgechev** [comment]
Nice point! MIT works prefectly.

**Comment by jonkri** [comment]
Excellent! Thanks! :)
