### ISSUE TITLE
Naming services

### ISSUE THREAD

**Issue by icruces** [mgechev/angularjs-style-guide#162]
Hi,

I have a bit confusion about how to name services.

The Services section says:

> UpperCamelCase (PascalCase) for naming your services, used as constructor functions.

> ...

> lowerCamelCase for all other services.

However, the `Order` factory example uses UpperCamelCase but it is not used as constructor function (the injector injects an `Order` object). Shouldn't it use lowerCamelCase?

Thanks.

**Comment by mgechev** [comment]
Thanks for the catch! Fixed.
