### ISSUE TITLE
there may be a mispell

### ISSUE THREAD

**Issue by chbro** [mgechev/angularjs-style-guide#180]
In order to prevent problems with minification, you can automatically generate the array definition syntax from the standard one using tools like ng-annotate (and grunt task grunt-ng-annotate).

Another alternative will be to use $inject like:

angular
 .module('app')
 .controller('HomepageCtrl', ***Homepage***);

HomepageCtrl.$inject = ['$log', '$http', 'ngRoute'];

function HomepageCtrl($log, $http, ngRoute) {
 // ...
}

**Comment by mgechev** [comment]
Would you open a PR with the fix?

It should be HomepageCtrl not Homepage.

**Comment by tanmayrajani** [comment]
having been fixed in 3447cf4, this should be closed I guess! :)
