### ISSUE TITLE
Testing Guidelines

### ISSUE THREAD

**Issue by DavidSouther** [mgechev/angularjs-style-guide#28]
This doc needs testing guidelines. I know tests are in a huge state of flux, but Year Of Moo's post is still entirely correct, with minor changes to using Karma and Protractor to run Unit and E2E respectively.

http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html

**Comment by mgechev** [comment]
I believe we can close this issue. Using https://github.com/daniellmb/angular-test-patterns sounds reasonable.
