### ISSUE TITLE
Always including templates / partials along-side other code?

### ISSUE THREAD

**Issue by skawaguchi** [mgechev/angularjs-style-guide#79]
Further to the point of including HTML, CSS, and test files in the same package for directives, why not do the same thing for controllers? We've been doing it and find it helps the development flow quite a bit. When we run our build scripts (gulp-ngtemplate, htmlhint, etc.) it's easy enough to just target .html files, so we haven't seen the need for a separate partials directory.

**Comment by mgechev** [comment]
This makes sense as well. I'll include an example.
